
Layout/IndentationWidth:
  # Number of spaces for each indentation level.
  Width: 4
  IgnoredPatterns: []

AllCops:
  # Exclude:
  #   - "somedir/**/*"
  UseCache: false
  DefaultFormatter: progress
  DisplayStyleGuide: true
  DisplayCopNames: true
  TargetRubyVersion: 2.5

Style/FormatStringToken:
  EnforcedStyle: unannotated

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Naming/AsciiIdentifiers:
  Enabled: false

Naming/BinaryOperatorParameterName:
  Enabled: false

Naming/ClassAndModuleCamelCase:
  Enabled: false

Naming/ConstantName:
  Enabled: false

Naming/FileName:
  Enabled: false

Naming/HeredocDelimiterCase:
  Enabled: false

Naming/HeredocDelimiterNaming:
  Enabled: false

Naming/MemoizedInstanceVariableName:
  Enabled: false

Naming/MethodName:
  Enabled: false

Naming/PredicateName:
  Enabled: false

Naming/UncommunicativeBlockParamName:
  Enabled: false

Naming/UncommunicativeMethodParamName:
  Enabled: false

Naming/VariableName:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false