language: ruby
rvm:
  - 2.5.0
  - 2.0.0
  - 1.9.3
  - jruby-19mode
  - rbx-2
before_install:
  - gem list --local | grep bundler || gem install bundler
  - gem list --local | grep rake || gem install rake
install:
  - bundle exec rake
